### ISSUE TITLE
Export wallet

### ISSUE THREAD

**Issue by fgallaire** [creativechain/android-wallet#6]
There's no wallet.dat like in the other wallets, so I can't export my Android wallet to the Linux-Qt wallet.

**Comment by ander7agar** [comment]
There is a backup of your wallet in the external storage: 
`extDir/CreativeChain/Backcup/backup-protobuf.ccm`

I have to tell you that for now it is impossible to use a file from an android wallet with the desktop wallet (Linux/Win/Mac). It is only possible if private keys are imported from all addresses one by one, but this is a very tedious task.

We are currently working on some kind of compatibility, but we can not promise anything.
